baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
relativeURLs = true
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]
[params]
  client =                    "Client Name"
